---
title: "How to"
author: Romain Chailan - romain.chailan@gmail.com
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Install and load

```{r install-package, eval=FALSE}
# If you do not have it yet, download and install the package `iniestat` with
devtools::install_github("rchailan/iniestat", auth_token="374a0736a7bdb9e73117fe3d5eb10f9fa9d62790")
```

Do not forget to load the package in your environment with
```{r setup}
library(iniestat)
```

# Read F24 file(s)

The very first function you want to use is `iniestat::read_f24()`.
It allows either to read one file or several files from a folder in one command only.

```{r read-files, eval=FALSE}
# To read one file from one match
my_events <- iniestat::read_f24(file_path = "my_f24.xml")

# To read several files from several match and stored in a directory
my_events_multi_games <- iniestat::read_f24(dir_path = "my_f24_data/")
```

The later function will read all files and concatenate the events into one tibble.

# Read OPT file(s)

Still in dev.